### PR TITLE
Add ATLAS style dropdown component

### PR DESCRIPTION
**Pull request by Sporiff**
https://adjustcom.atlassian.net/browse/THC-809

### CODE REVIEW

**Comment by bzavhorodskyi** [comment]
Looks good for me. I guess we will add support for dark mode later, cause currently page displaying like this: 
image
image

**Review by bzavhorodskyi — APPROVED** [review]

**Comment by bzavhorodskyi** [comment]
One more point, we can use typescript components here, it`s just for code accordance cause we are using TS in Astro components and other files: 
image

**Comment by Sporiff** [comment]
> One more point, we can use typescript for React components, it`s just for code accordance cause we are using TS in Astro components and other files

Good shout. I'll put in a followup PR to move these to `.tsx`. @bzavhorodskyi 

> Looks good for me. I guess we will add support for dark mode later

Yeah we'll need to do a whole theming project later on to fit the designs we had drawn up. We can tackle this then

**Comment by bzavhorodskyi** [comment]
> > One more point, we can use typescript for React components, it`s just for code accordance cause we are using TS in Astro components and other files
> 
> Good shout. I'll put in a followup PR to move these to `.tsx`. @bzavhorodskyi
> 
> > Looks good for me. I guess we will add support for dark mode later
> 
> Yeah we'll need to do a whole theming project later on to fit the designs we had drawn up. We can tackle this then

I`ve made updates to my comment so you can use it as a reference

**Pull request merged**
