### PR TITLE
Reformat iOS & Android instructions Tabs as standard sections

### PR DESCRIPTION
**Pull request by ironnysh**
## Related issues

- Jira issue link: [ADAPP-18952](https://adjustcom.atlassian.net/browse/ADAPP-18952)

## Changes

In the Unity integration app, under Build your app, there were tabs for iOS and Android. Both have internal headings with the same “names” and anchor links, creating a weird duplication/broken links in the internal ToC (the one on the right).

Extracted the iOS & Android instructions into standard sections in the document, and deleted the `tabs` component.

## Required translations

No text changed.

[ADAPP-18952]: https://adjustcom.atlassian.net/browse/ADAPP-18952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ironnysh** [comment]
@Sporiff There's a weird build error on Vercel:
```
[11:48:33.594] The requested module '../../../../en/sdk/unity/v4/index.render.mjs' does not provide an export named '__0__images_unity_1_prefab_png__'
[11:48:33.594]   Stack trace:
[11:48:33.594]     at ModuleJob._instantiate (node:internal/modules/esm/module_job:146:21)
[11:48:33.594]     at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
[11:48:33.594]     at async file:///vercel/path0/dist/pages/_lang_/_---slug_.astro.mjs?time=1731581277497:499:33
[11:48:33.594]     at async renderToString (file:///vercel/path0/node_modules/astro/dist/runtime/server/render/astro/render.js:8:26)
[11:48:33.594]     at async lastNext (file:///vercel/path0/node_modules/astro/dist/core/render-context.js:146:25)
[11:48:33.687] Error: Command "npm run build" exited with 1
[11:48:34.170] 
```

I ran into it locally and it "resolved" by deleting the image reference and pasting it back:
```
![A screenshot of the Adjust SDK post-build configuration script in the Unity editor.](@images/unity/2-postbuild.png)
```

Not sure what/where is the problem. It's not something related to the changes I made.

**Review by Sporiff — APPROVED** [review]
@ironnysh LGTM 👍  The error is caused by a combination of MDX and the content collection cache. It can be fixed by simply rebuilding with no cache, so I've done that now.

**Comment by ironnysh** [comment]
Ah, got it :-)

> rebuilding with no cache

That's on Vercel's side, right? (for future me...)

**Comment by Sporiff** [comment]
> That's on Vercel's side, right? (for future me...)

@ironnysh Correct. The build can be rerun with no cache by simply hitting "Redeploy". Currently only me and Bohdan can do that, but at some point we'll have a generic login that we share.

If it continues to cause issues, we might just disable the experimental content cache. It might be worth investigating ISG instead of SSG for incremental deployments, but that has its own caveats.

**Pull request merged**
