### PR TITLE
Update and Fix iOS v5 code snippets

### PR DESCRIPTION
**Pull request by Aditi3**
- Updated iOS code snippets for v5 integration and migration guide
- Majorly improvised Swift code snippets
- Fixed Obj-C code snippets in some places

### CODE REVIEW

**Comment by Aditi3** [comment]
@Sporiff Could you help me to add a new section for Swift code snippet here - https://dev.adjust.com/en/sdk/ios/features/short-links?version=v5#set-up-the-adjust-sdk-to-resolve-short-links

**Comment by Sporiff** [comment]
@Aditi3 lmk when you're finished and I'll review/merge 👍

**Comment by Aditi3** [comment]
Hey @Sporiff, I'm finished with my changes. Could you help to resolve the preview deployment failure message?

**Review by Sporiff — APPROVED** [review]
@Aditi3 Fixed. LGTM! Merging now.

**Pull request merged**
